# Generated by Django 3.1.3 on 2021-11-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Luz', models.IntegerField()),
                ('Humedad', models.IntegerField()),
                ('Fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
